### ISSUE TITLE
Feature request: highlight words that occur with an unusual frequency

### ISSUE THREAD

**Issue by Kazark** [reedes/vim-wordy#16]
In my writing, one bad behavior I have is to use the same word or phrase over and over. Often I don't even realize I'm doing it. It would be nice to have a Wordy feature that looked for words or phrases being used an excessive number of time in comparison to the overall document length, excluding of course small connector words.

I know this is someone of a vague suggestion and would need to be hammered down, but it would be extremely useful to me.

**Comment by reedes** [comment]
That could be very useful, but I'd encourage its development as a separate plugin. Three reasons:

Wordy's implementation is tied tightly to spell files. Extending it to support other kinds of matching risks turning it into a kitchen sink plugin that lacks focus.

Also, it's not clear if spell file support will be in neovim, which would exclude wordy, so I'd avoid the dependency on that ground alone.

Plugins with a tight focus are more comprehensible to users, and thus should gain broader adoption.

**Comment by Kazark** [comment]
Makes sense.
