### ISSUE TITLE
Conversion failure when creating word file

### ISSUE THREAD

**Issue by davidcbenson** [reedes/vim-wordy#27]
OS: Windows 10
Vim Version: Vim 8

Problem description:

When calling a Wordy list for the first time, I get a few 
> "Conversion failure for word in ~/vimfiles/bundle/vim-wordy/data/en/puffery.dic line [0-9]" messages. (the line and the dictionary will vary) 

In every case it seems that the problem is "curly quotes" which appear as gibberish characters within the word that failed to convert. I'm guessing there is a simple fix, but I cannot figure it out.

**Comment by reedes** [comment]
Sorry, but I haven't had a chance to test wordy in Windows.

It's likely a codepage mapping issue, where I haven't a clue where to start in debugging it. 

If you do have time to dig into problem and find a fix, a pull request is welcome.

**Comment by davidcbenson** [comment]
I'll take a look, but I am actually a vim neophyte, so I don't know that it will yield fruit. When I looked at the files, I got a ton of gibberish.

On a unrelated note (and I'm happy to start a new thread if you'd prefer) I am an instructor at a military institution, and I would be interested in creating a list of military jargon/acronyms/common -isms. While I understand the idea of adding my own key-ring, is there way to help contribute an entire list? (e.g. a wordy-military list)

**Comment by reedes** [comment]
Sorry for the delay.

I'd like to avoid adding more domain-specific lists to the default ones, but wordy needs a better way to accommodate them. I'll think about how best to do that.

**Comment by davidcbenson** [comment]
That's quite reasonable. One option is to allow pull requests of vocabulary for the lists. In my case, for example, a separate domain-specific list may not be necessary, as military vocab is jargon, is sometimes replicated in other circumstances, and is unlikely to clash with other jargon on the list.

If you are already doing this, I apologize. As noted, I am a vim neophyte, and have seldom used git collaboratively, and therefore am not always able to discern what is working, or not.
