### ISSUE TITLE
Wordy doesn't work; invalid argument spelllang=en,/.....

### ISSUE THREAD

**Issue by ntguardian** [reedes/vim-wordy#33]
When I type `:Wordy redundant` or basically any `wordy` command I get something like the following (except maybe I don't get the rebuild):

```
Reading word file /home/curtis/.vim/plugged/vim-wordy/data/en/redundant.dic...                                          
Compressing word tree...
Compressed 1190 of 3937 nodes; 2747 (69%) remaining
Writing spell file /home/curtis/.vim/plugged/vim-wordy/spell/redundant.en.utf-8.spl...
Done!
Estimated runtime memory use: 13735 bytes
Error detected while processing function wordy#init:
line   60:
E474: Invalid argument: spelllang=en,/home/curtis/.vim/plugged/vim-wordy/spell/redundant.en.utf-8.spl
Press ENTER or type command to continue
```

**Comment by stefmitropoulos** [comment]
You are not alone! Have this too in other words...

**Comment by lordievader** [comment]
Same problem here. I get the feeling this is due to an update with vim. More things broke with a recent update. I'm currently running `8.0.1298`.

**Comment by mys721tx** [comment]
MacVim `8.1.722` also has the same problem. Is it a problem with the upstream or that `vim-wordy` was depending on a particular behavior of the older version?

**Comment by frrobert2** [comment]
Same issue on 8.1.192 running on Ubuntu 16.04.  I compiled using the Huge switch.

**Comment by frrobert2** [comment]
I tried bcl's commit and it word great for me.  Thank you

**Comment by lordievader** [comment]
I tried it too. Loaded via Vim's native plugin support. Fixes this issue.

**Comment by reedes** [comment]
Applied bcl's patch to master. Sorry for the delay.
