### ISSUE TITLE
Update the demo gif to replace deprecated commands

### ISSUE THREAD

**Issue by reedes** [reedes/vim-wordy#9]
For example, rather than `:WeakWordy`, it should use `:Wordy weak` or the ring.

**Comment by michaelx386** [comment]
How does this look? Happy to redo it if you have any suggestions:

![demo](http://i.imgur.com/WDk141d.gif)

[http://i.imgur.com/WDk141d.gif](http://i.imgur.com/WDk141d.gif)

**Comment by reedes** [comment]
Nice work.

The only suggestion I have is to simplify:
- pull art-jargon out of your ring, as it's not adding anything to the example
- contractions, etc. and problematic, etc. don't add much either

**Comment by michaelx386** [comment]
Thank you, I've removed those three items from the demo:

![demo](http://i.imgur.com/cXDCwdE.gif)

[http://i.imgur.com/cXDCwdE.gif](http://i.imgur.com/cXDCwdE.gif)

Let me know if you want anymore taken out or any other tweaks. I can create a pull request to add the new imgur url to the readme file, should I remove the old screenshots folder too?

**Comment by reedes** [comment]
Looks great. Please do create a pull request.

Thanks!

**Comment by reedes** [comment]
Please leave the demo.txt in the screenshots folder, as it's my reminder of how to re-create the demo gif should it be necessary again in the future.
